// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930185639_Agregar-Auditoria-Forenea-DocumentoPago")]
    partial class AgregarAuditoriaForeneaDocumentoPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Auditorias.Auditoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("appCreador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("documentoPagoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("hostCreador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("usuarioCreadorId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("documentoPagoId");

                    b.ToTable("Auditoria", "sch_gespago");
                });

            modelBuilder.Entity("Domain.DocumentosPagos.DocumentoPago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("pagoMasivoId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("DocumentoPago", "sch_gespago");
                });

            modelBuilder.Entity("Domain.Auditorias.Auditoria", b =>
                {
                    b.HasOne("Domain.DocumentosPagos.DocumentoPago", "documentoPago")
                        .WithMany()
                        .HasForeignKey("documentoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("documentoPago");
                });
#pragma warning restore 612, 618
        }
    }
}
